version: '2'
services:
  zookeeper:
    container_name: zookeeper-server
    image: quay.io/debezium/zookeeper:2.1
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    container_name: kafka-server
    image: quay.io/debezium/kafka:2.1
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    links:
      - kafka  
  mysql-dbx:
    container_name: DBXDB
    image: quay.io/debezium/example-mysql:2.1
    #image: mysql:5.7
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_DATABASE=dbxdb
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
  mysql-core:
    container_name: T24DB
    image: quay.io/debezium/example-mysql:2.1
    ports:
     - 3307:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_DATABASE=t24db
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw   
  connect_source:
    container_name: mysql-source
    image: quay.io/debezium/connect:2.1
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql-dbx
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_source_connect_configs
     - OFFSET_STORAGE_TOPIC=my_source_connect_offsets
  # connect_sink:
  #   container_name: mysql-sink
  #   build: 
  #     context: debezium-jdbc
  #   ports:
  #    - 8084:8083
  #   links:
  #    - kafka
  #    - mysql-core
  #   environment:
  #    - BOOTSTRAP_SERVERS=kafka:9092
  #    - GROUP_ID=1
  #    - CONFIG_STORAGE_TOPIC=my_sink_connect_configs
  #    - OFFSET_STORAGE_TOPIC=my_sink_connect_offsets
